### ISSUE TITLE
sdm845: Maximum frequency error on big cluster

### ISSUE THREAD

**Issue by jjpprrrr** [kdrag0n/freqbench#4]
Freqbench stopped after about 20 minutes and rebooted to fastboot. I was only able to get two files from `/cache/freqbench` directory: `pre_bench_interrupts.txt` and `run.log`. `run.log` has all frequency results for CPU1 but failed on CPU4.

```

  __                _                     _     
 / _|_ __ ___  __ _| |__   ___ _ __   ___| |__  
| |_| '__/ _ \/ _` | '_ \ / _ \ '_ \ / __| '_ \ 
|  _| | |  __/ (_| | |_) |  __/ | | | (__| | | |
|_| |_|  \___|\__, |_.__/ \___|_| |_|\___|_| |_|
                 |_|                            

           CPU benchmark • by kdrag0n

------------------------------------------------

Frequency domains: cpu1 cpu4 
Offline CPUs: cpu1 cpu2 cpu3 cpu4 cpu5 cpu6 cpu7 
Sampling power every 1000 ms
Baseline power usage: 1288 mW


===== CPU 1 =====
Frequencies: 300 403 480 576 652 748 825 902 979 1056 1132 1228 1324 1420 1516 1612 1689 1766

 300:  1114     3.7 C/MHz     56 mW   12.7 J   19.8 I/mJ   224.5 s
 403:  1497     3.7 C/MHz     48 mW    8.1 J   31.0 I/mJ   167.0 s
 480:  1782     3.7 C/MHz     51 mW    7.2 J   34.9 I/mJ   140.3 s
 576:  2138     3.7 C/MHz     60 mW    7.0 J   35.8 I/mJ   116.9 s
 652:  2424     3.7 C/MHz     63 mW    6.5 J   38.5 I/mJ   103.2 s
 748:  2780     3.7 C/MHz     64 mW    5.7 J   43.5 I/mJ    89.9 s
 825:  3065     3.7 C/MHz     84 mW    6.8 J   36.6 I/mJ    81.6 s
 902:  3350     3.7 C/MHz     73 mW    5.5 J   45.7 I/mJ    74.6 s
 979:  3635     3.7 C/MHz     93 mW    6.4 J   38.9 I/mJ    68.8 s
1056:  3921     3.7 C/MHz    102 mW    6.5 J   38.5 I/mJ    63.8 s
1132:  4205     3.7 C/MHz    107 mW    6.4 J   39.1 I/mJ    59.5 s
1228:  4562     3.7 C/MHz    119 mW    6.5 J   38.4 I/mJ    54.8 s
1324:  4918     3.7 C/MHz    152 mW    7.7 J   32.4 I/mJ    50.8 s
1420:  5275     3.7 C/MHz    132 mW    6.3 J   39.9 I/mJ    47.4 s
1516:  5631     3.7 C/MHz    155 mW    6.9 J   36.4 I/mJ    44.4 s
1612:  5988     3.7 C/MHz    147 mW    6.1 J   40.8 I/mJ    41.8 s
1689:  6273     3.7 C/MHz    150 mW    6.0 J   41.8 I/mJ    39.9 s
1766:  6558     3.7 C/MHz    172 mW    6.6 J   38.1 I/mJ    38.1 s


===== CPU 4 =====
Traceback (most recent call last):
  File "/bench.py", line 479, in <module>
    main()
  File "/bench.py", line 335, in main
    raise ValueError(f"Maximum frequency setting {max(freqs)} rejected by kernel; got {real_max_freq}")
ValueError: Maximum frequency setting 2649600 rejected by kernel; got 1286400
```

Are there any other commits I need to revert, or configs I did not turn off? I used a modified lineage xiaomi sdm845 kernel ([link](https://github.com/lineageos/android_kernel_xiaomi_sdm845))with HEAD at `fd19a6e41bc486f0ae82e55112c4618049b52d5b`. 

I added/changed the following configs for polaris_defconfig:
```
CONFIG_DEVTMPFS=y
CONFIG_NO_HZ_FULL=y
CONFIG_CPU_FREQ_STAT=n
CONFIG_CPU_FREQ_TIMES=n
```

**Comment by jjpprrrr** [comment]
The above error happened during the first two runs. The third run lasted at least 35 minutes, way longer than the previous two runs, so I assume it got pass the frequency check and started running on the big cluster. However, after about 35 minutes, the phone rebooted again back to splash, not bootloader, which seemed to be a kernel panic? I am now on the fourth run.

**Comment by jjpprrrr** [comment]
Ok I guess after finishing benchmark, the phone is supposed to reboot back to splash? I force rebooted back to recovery after the 4th run, and was able to retrieve all test results. The run.log says "Benchmark finished!".

**Comment by jjpprrrr** [comment]
`cpufreq_stats/0` and `cpufreq_stats/4` are both empty. Other files seem to contain valid data.

**Comment by attack11** [comment]
@jjpprrrr maybe some results are empty cause you forced the reboot,check the pull request Ive just done to boot to recovery once the bench has finished

**Comment by jjpprrrr** [comment]
@attack11 Thanks. I just did the same thing locally haha.

**Comment by jjpprrrr** [comment]
Nope. This time it reboots back to recovery, and the result still doesn't have cpufreq_stats. I also checked the code, and `save_logs` is run at the end, so me rebooting at the start of next run should not affect anything anyway. I can manually cat the cpufreq_stats, so I don't know why it's not in the result.

**Comment by jjpprrrr** [comment]
Nevermind. I'm dumb. I turned off CONFIG_CPU_FREQ_STAT so of course that folder is empty.

**Comment by kdrag0n** [comment]
You need to make sure the kernel is not setting any minimum or maximum frequencies by itself. Boosting-related changes will often do this.

I just pushed a commit to wait before validating the frequency limits in case it was caused by a race condition, so you might want to test that first. If that doesn't fix it, look for problematic commits in your kernel.

**Comment by jjpprrrr** [comment]
@kdrag0n Thanks for the reply. It only happened during the first two runs. Subsequent runs were all good. I have got four sets of results and will soon start examining them and preparing for PR.

**Comment by jjpprrrr** [comment]
Another thing I noticed is that the bench reads frequencies from scaling_available_frequencies. Therefore, frequencies in scaling_boost_frequencies (2803200 on sdm845 for example) are not tested. Is this the intended behavior? Are there any ways of getting the boot frequency power as well?

**Comment by jjpprrrr** [comment]
Opened a PR to add boost frequencies to the bench. #6

**Comment by kdrag0n** [comment]
Thanks for the info and PR. That confirms that the maximum frequency issue was a race condition, so I've added a delay to stop it from happening. Boost frequencies are also included now, and init will try to save system info even if the benchmark fails, so all of your issues should be addressed.
